sylius_twig_hooks:
    hooks:
        'sylius_cms.admin.page.update.content':
            form:
                component: 'sylius_cms:admin:page:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusCmsPlugin/admin/page/form.html.twig'
                configuration:
                    method: 'PUT'
                priority: 0

        'sylius_cms.admin.page.update.content.form':
            header:
                template: '@SyliusCmsPlugin/admin/page/form/header.html.twig'
                priority: 100
            sections:
                template: '@SyliusCmsPlugin/admin/page/form/sections.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.header':
            summary:
                template: '@SyliusCmsPlugin/admin/page/form/header/summary.html.twig'
                priority: 100
            navigation:
                template: '@SyliusCmsPlugin/admin/page/form/header/navigation.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.header.summary':
            title:
                template: '@SyliusCmsPlugin/admin/page/form/header/summary/title.html.twig'
                priority: 200
            status:
                template: '@SyliusCmsPlugin/admin/page/form/header/summary/status.html.twig'
                priority: 100
            meta:
                template: '@SyliusCmsPlugin/admin/page/form/header/summary/meta.html.twig'
                priority: 50
            preview:
                template: '@SyliusCmsPlugin/admin/shared/preview/render.html.twig'
                configuration:
                    button_class: 'btn'
                priority: 0

        'sylius_cms.admin.page.update.content.form.header.navigation':
            tabs:
                template: '@SyliusCmsPlugin/admin/page/form/header/navigation/tabs.html.twig'
                priority: 100
            locale_switcher:
                template: '@SyliusCmsPlugin/admin/page/form/header/navigation/locale_switcher.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.header.navigation.tabs':
            content:
                template: '@SyliusCmsPlugin/admin/page/form/header/navigation/tabs/tab.html.twig'
                configuration:
                    tab: 'content'
                    active: true
                    elements_count: true
                priority: 300
            teaser:
                template: '@SyliusCmsPlugin/admin/page/form/header/navigation/tabs/tab.html.twig'
                configuration:
                    tab: 'teaser'
                priority: 200
            seo:
                template: '@SyliusCmsPlugin/admin/page/form/header/navigation/tabs/tab.html.twig'
                configuration:
                    tab: 'seo'
                priority: 100
            settings:
                template: '@SyliusCmsPlugin/admin/page/form/header/navigation/tabs/tab.html.twig'
                configuration:
                    tab: 'settings'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections':
            general:
                enabled: false
            content:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content.html.twig'
                configuration:
                    active: true
                priority: 300
            teaser:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser.html.twig'
                priority: 200
            seo:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo.html.twig'
                priority: 100
            settings:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.content':
            translations:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/translations.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.content.translations':
            structure:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/translations/structure.html.twig'
                priority: 100
            editor:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/translations/editor.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.content.translations.structure':
            elements_template:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/translations/structure/elements_template.html.twig'
                priority: 100
            elements:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/translations/structure/elements.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.content.translations.editor':
            elements:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/translations/editor/elements.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.teaser':
            translations:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/translations.html.twig'
                priority: 100
            aside:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/aside.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.teaser.aside':
            tile_preview:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/aside/tile_preview.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.teaser.translations':
            title:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/translations/title.html.twig'
                priority: 200
            content:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/translations/content.html.twig'
                priority: 100
            image:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/translations/image.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.seo':
            translations:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations.html.twig'
                priority: 100
            aside:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/aside.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.seo.aside':
            search_preview:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/aside/search_preview.html.twig'
                priority: 100
            locales:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/aside/locales.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.seo.translations':
            meta_title:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations/meta_title.html.twig'
                priority: 200
            slug:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations/slug.html.twig'
                priority: 300
            meta_keywords:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations/meta_keywords.html.twig'
                priority: 0
            meta_description:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations/meta_description.html.twig'
                priority: 100

        'sylius_cms.admin.page.update.content.form.sections.settings':
            general:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/general.html.twig'
                priority: 200
            organization:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/organization.html.twig'
                priority: 100
            publishing:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/publishing.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.settings.general':
            code:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/general/code.html.twig'
                priority: 100
            name:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/general/name.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.settings.organization':
            template:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/organization/template.html.twig'
                priority: 100
            collections:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/organization/collections.html.twig'
                priority: 0

        'sylius_cms.admin.page.update.content.form.sections.settings.publishing':
            enabled:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/publishing/enabled.html.twig'
                priority: 200
            publish_at:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/publishing/publish_at.html.twig'
                priority: 100
            channels:
                template: '@SyliusCmsPlugin/admin/page/form/sections/settings/publishing/channels.html.twig'
                priority: 0
